#!/bin/sh

for item in $(find dot ! -ipath '**/.*'); do
  target=~/`echo $item | sed -e 's@dot/*@.@'`

  if [ -d $item ]; then
    test -d $target || mkdir -p $target
  elif [ -f $item ]; then
    echo "Copying ${item} to ${target}" 
    cp $item $target
  fi
done

mkdir -p ~/bin

for item in $(ls bin); do
  target=~/bin/$item
  echo "Copying bin/${item} to ${target}"   
  cp ./bin/$item $target
done

. ~/.bashrc
