#!/bin/sh

for item in $(find home ! -ipath '**/.*'); do
  target=~/`echo $item | sed -e 's/home\///' -e 's@dot/*@.@'`

  if [ -d $item ]; then
    test -d $target || mkdir -p $target
  elif [ -f $item ]; then
    echo "Copying ${item} to ${target}" 
    cp $item $target
  fi
done

# Update environment
. ~/.bashrc
