color ir_black
hi ColorColumn guibg=#222222

set guifont=Inconsolata:h18
set guioptions=egmrt
set ruler

" unmap default command-T tab behavior
macmenu &File.New\ Tab key=<nop>

" unmap default command-} tab next
macmenu Window.Select\ Next\ Tab key=<nop>

" unmap default command-{ tab previous
macmenu Window.Select\ Previous\ Tab key=<nop>
