runtime pathogen/autoload/pathogen.vim

call pathogen#infect()
call pathogen#helptags()

set nocompatible
set hidden

set directory=~/.vim/tmp
set nocompatible
set encoding=utf-8
set showcmd

set nowrap
set tabstop=2 shiftwidth=2
set expandtab
set backspace=indent,eol,start
set paste

set list
set listchars=""
set listchars=tab:..
set listchars+=trail:.
set listchars+=extends:>
set listchars+=precedes:<

set hlsearch
set incsearch
set ignorecase
set smartcase

set textwidth=80
set colorcolumn=80
set ruler
set number
set laststatus=2
set numberwidth=4
set autoindent

set undofile
set undodir=/tmp

set wildmode=longest,list,full
set wildmenu

filetype plugin indent on
syntax enable

color desert

" leader-n to toggle NERDTree
:map <leader>n :execute 'NERDTreeToggle ' . getcwd()<CR>

" command-/ to toggle comments via NERDCommenter
nmap <D-/> <leader>c<space>
vmap <D-/> <leader>c<space>
imap <D-/> <C-O><leader>c<space>

" leader-/ to :nohlsearch
map <leader>/ :nohlsearch<CR>

" command-T to command-T plugin
nnoremap <silent> <Leader>t :CommandT<CR>
nnoremap <silent> <Leader>b :CommandTBuffer<CR>
map <D-t> :CommandT<CR>
map <D-T> :CommandTBuffer<CR>

" command-R to copy the current filename to the clipboard (relative path)
:map <D-R> :let @*=expand("%")<CR>

" command-A to copy the current filename to the clipboard (absolute path)
:map <D-A> :let @*=expand("%:p")<CR>

" command-L to copy the current filename and line number to the clipboard
:map <D-L> :let @*=expand("%:p") . ":" . <C-r>=line('.')<CR><CR>

" move through open buffers
nmap <D-{> :bprev<CR>
nmap <D-}> :bnext<CR>

" move through window splits
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" make Y act like C, D et al and map to y$
map Y y$

" remap ; to : for maximum laziness
nnoremap ; :
vnoremap ; :
