runtime pathogen/autoload/pathogen.vim

call pathogen#infect()
call pathogen#helptags()

set nocompatible
set hidden

set directory=~/.vim/tmp
set nocompatible
set encoding=utf-8
set showcmd

set nowrap
set tabstop=2 shiftwidth=2
set expandtab
set backspace=indent,eol,start
set paste

set list
set listchars=""
set listchars=tab:..
set listchars+=trail:.
set listchars+=extends:>
set listchars+=precedes:<

set hlsearch
set incsearch
set ignorecase
set smartcase

set textwidth=80
set colorcolumn=80
set ruler
set number
set numberwidth=4
set autoindent

filetype plugin indent on
syntax enable

color desert

function! RSpec(args)
 execute ":silent ! run-in-terminal.applescript 'rspec " . a:args . " %'"
endfunction

" leader-n to toggle nerdtree
:map <leader>n :execute 'NERDTreeToggle ' . getcwd()<CR>

" leader-cs to copy the current filename to the clipboard (relative path)
:map <leader>cs :let @*=expand("%")<CR>

" leader-cp to copy the current filename to the clipboard (absolute path)
:map <leader>cp :let @*=expand("%:p")<CR>

" leader-cl to copy the current filename and line number to the clipboard
:map <leader>cl :let @*=expand("%:p") . ":" . <C-r>=line('.')<CR><CR>

" command-R to run a focused spec
map <D-R> :call RSpec("-l " . <C-r>=line('.')<CR>)<CR>

" command-r to run all specs
map <D-r> :call RSpec("")<CR>

" command-/ to toggle comments via NERDCommenter
nmap <D-/> <leader>c<space>
vmap <D-/> <leader>c<space>
imap <D-/> <C-O><leader>c<space>

" <return> to :nohlsearch
map <return> :nohlsearch<CR>

" command-T to command-T plugin
nnoremap <silent> <Leader>t :CommandT<CR>
nnoremap <silent> <Leader>b :CommandTBuffer<CR>

map <D-t> :CommandT<CR>
map <D-T> :CommandT<CR>
