alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias ws="cd ~/workspace"

export PATH=${PATH}:${HOME}/bin
export EDITOR="nvim"
export VISUAL="nvim"
export ZSH="${HOME}/.oh-my-zsh"
export ZSH_THEME="agnoster"

plugins=(git)

source ${ZSH}/oh-my-zsh.sh

if [ -r ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi
