export VISUAL="nvim"
export EDITOR="nvim"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="agnoster"

plugins=(git)
source $ZSH/oh-my-zsh.sh

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias ws="cd ~/workspace"

if [ -r ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi
