export VISUAL="nvim"
export EDITOR="nvim"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="agnoster"

source $ZSH/oh-my-zsh.sh

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias ws="cd ~/workspace"

prompt_context(){
  prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
} 

if [ -r ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi
